default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: game_dev

test:
  <<: *default
  database: game_test

production:
  <<: *default
  database: game_prod
